version: "3.3"
services:
#  api-be-java:
#    image: 'api-be-java:latest'
#    container_name: api-be-java
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.0.104:5432/postgres
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=123456
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
##    restart: always
#    volumes:
#      - /home/hieuptit/Desktop/worker/api/src/main/resources:/usr/app
#    command:
#      - --config.file=/usr/app/application.yml
##      - ./application.properties:/usr/app/application.properties
#    ports:
#      - 8021:8021
#    network_mode:  bridge
#  zookeeper:
#    image: 'bitnami/zookeeper:latest'
#    ports:
#      - '12181:2181'
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#  kafka:
#    image: 'bitnami/kafka:latest'
#    ports:
#      - '9093:9093'
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
#      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
#      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
#      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
#    depends_on:
#      - zookeeper
  postgres:
    image: 'postgres:latest'
#    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
#networks:
#    host:
#      external:
#        name: "host"
#    external: true

