
server:
  port: '8021'
  error:
    include-binding-errors: always
    include-message: always
management:
  security:
    enabled: false
management.endpoint.health.probes.enabled: true

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: 123456
  mvc:
    async:
      request-timeout: 120000
  flyway:
    baseline-on-migrate: true
    url: "jdbc:postgresql://localhost:5432/postgres"
    user: postgres
    password: 123456
    locations: classpath:db/migration

